// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/alert/index":{"id":"components/alert/index","path":"components/alert","parentId":"DocLayout","meta":{"_atom_route":true}},"components/card/index":{"id":"components/card/index","path":"components/card","parentId":"DocLayout","meta":{"_atom_route":true}},"components/searchDefault/index":{"id":"components/searchDefault/index","path":"components/search-default","parentId":"DocLayout","meta":{"_atom_route":true}},"components/select/index":{"id":"components/select/index","path":"components/select","parentId":"DocLayout","meta":{"_atom_route":true}},"components/tycontainer/index":{"id":"components/tycontainer/index","path":"components/tycontainer","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/ruhnn/项目测试/happy-ui/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/ruhnn/项目测试/happy-ui/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/ruhnn/项目测试/happy-ui/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/ruhnn/项目测试/happy-ui/docs/index.md')),
'components/alert/index': React.lazy(() => import(/* webpackChunkName: "alert__index.md" */'/Users/ruhnn/项目测试/happy-ui/src/alert/index.md')),
'components/card/index': React.lazy(() => import(/* webpackChunkName: "card__index.md" */'/Users/ruhnn/项目测试/happy-ui/src/card/index.md')),
'components/searchDefault/index': React.lazy(() => import(/* webpackChunkName: "searchDefault__index.md" */'/Users/ruhnn/项目测试/happy-ui/src/searchDefault/index.md')),
'components/select/index': React.lazy(() => import(/* webpackChunkName: "select__index.md" */'/Users/ruhnn/项目测试/happy-ui/src/select/index.md')),
'components/tycontainer/index': React.lazy(() => import(/* webpackChunkName: "tycontainer__index.md" */'/Users/ruhnn/项目测试/happy-ui/src/tycontainer/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/ruhnn/项目测试/happy-ui/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
