// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/ruhnn/项目测试/happy-ui/node_modules/dumi/theme-default/slots/LangSwitch/index.js';
