// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/ruhnn/项目测试/happy-ui/docs/index.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/ruhnn/项目测试/happy-ui/docs/index.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/ruhnn/项目测试/happy-ui/src/alert/index.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/ruhnn/项目测试/happy-ui/src/alert/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/ruhnn/项目测试/happy-ui/src/card/index.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/ruhnn/项目测试/happy-ui/src/card/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/ruhnn/项目测试/happy-ui/src/searchDefault/index.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/ruhnn/项目测试/happy-ui/src/searchDefault/index.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/ruhnn/项目测试/happy-ui/src/select/index.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/ruhnn/项目测试/happy-ui/src/select/index.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/ruhnn/项目测试/happy-ui/src/tycontainer/index.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/ruhnn/项目测试/happy-ui/src/tycontainer/index.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/ruhnn/项目测试/happy-ui/src/virtualizedList/index.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/ruhnn/项目测试/happy-ui/src/virtualizedList/index.md?type=demo-index';

export const filesMeta = {
  'docs/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/ruhnn/项目测试/happy-ui/docs/index.md?type=text'),
  },
  'components/alert/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__alert" */'/Users/ruhnn/项目测试/happy-ui/src/alert/index.md?type=text'),
  },
  'components/card/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__card" */'/Users/ruhnn/项目测试/happy-ui/src/card/index.md?type=text'),
  },
  'components/searchDefault/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__searchDefault" */'/Users/ruhnn/项目测试/happy-ui/src/searchDefault/index.md?type=text'),
  },
  'components/select/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__select" */'/Users/ruhnn/项目测试/happy-ui/src/select/index.md?type=text'),
  },
  'components/tycontainer/index': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__tycontainer" */'/Users/ruhnn/项目测试/happy-ui/src/tycontainer/index.md?type=text'),
  },
  'components/virtualizedList/index': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__virtualizedList" */'/Users/ruhnn/项目测试/happy-ui/src/virtualizedList/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
